# Generated by Django 2.1.7 on 2020-07-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
